### PR TITLE
(#62) Added Minecraft root to be set by system environment variable

### PR DESCRIPTION
**Pull request by JayPankajPatel**
## Summary

Reads in environment variable to run enderchest command 
Addresses #62 

## List of Changes

* Added system env var to specify root https://github.com/JayPankajPatel/EnderChest/blob/877c65e61adc74eef77e149f2849fab67e2ee8f4/enderchest/cli.py#L613-L620
* Added mocks to test system env var as valid root https://github.com/JayPankajPatel/EnderChest/blob/877c65e61adc74eef77e149f2849fab67e2ee8f4/enderchest/test/test_cli.py#L80-L83
* Updated Documentation to reflect changes https://github.com/JayPankajPatel/EnderChest/blob/877c65e61adc74eef77e149f2849fab67e2ee8f4/docs/usage.md?plain=1#L32-L35

## Validation Performed

* Used mocks to verify if root was set to the env variable
## PR Type

- [ ] This PR introduces a breaking change (will
  [require a bump in the minor version](https://semver.org/))
- [ ] The changes in this PR are high urgency and necessitate a hotfix or patch
  release (will require rebasing off of `release`)
- [ ] This is a release (staging) PR (maintainer use only)

## Checklist:

- [x] I have read [the contributor's guide](https://openbagtwo.github.io/EnderChest/dev/contrib/)
- [ X] I have run `mkdocs serve` locally and ensured that all API docs and
  changes I have made to the static pages are rendering correctly, with all links
  working
- [X] All tech debt concerns have been resolved, documented as issues, or otherwise
  accepted
- [X] I agree to license my contribution to this project under
  [the GNU Public License v3](https://www.gnu.org/licenses/gpl-3.0.en.html)

### CODE REVIEW

**Comment by OpenBagTwo** [comment]
Tested this out on my local installation:

```bash
$ MINECRAFT_ROOT=/actual/path/to/my/minecraft enderchest open
```
ran my `open` operation

```bash
$ MINECRAFT_ROOT=~/.minecraft enderchest list
```

(where `/home/openbagtwo/.minecraft` was a symlink pointing to my minecraft folder) resolved the "~," followed the symlink and listed out my shulker boxes.

So: LGTM! There's just a little bit of [formatting](https://github.com/OpenBagTwo/EnderChest/actions/runs/6228804701/job/16937883777?pr=93) you need to do.

If you have [pre-commit or black installed on development box](https://openbagtwo.github.io/EnderChest/dev/contrib/#setting-up-a-development-environment), then:

```bash
pre-commit run --all
```
will reformat the two files.

If you don't / can't, then here's the diff you need to implement:

```diff
diff --git a/enderchest/cli.py b/enderchest/cli.py
index 9c91c68..7b71c2d 100644
--- a/enderchest/cli.py
+++ b/enderchest/cli.py
@@ -613,11 +613,11 @@ def parse_args(argv: Sequence[str]) -> tuple[Action, Path, int, dict[str, Any]]:
             MINECRAFT_ROOT = os.getenv("MINECRAFT_ROOT")
 
             return (
-                    actions[aliases[command]],
-                    Path(root_arg or root_flag or MINECRAFT_ROOT or os.getcwd()),
-                    log_level,
-                    action_kwargs,
-                    )
+                actions[aliases[command]],
+                Path(root_arg or root_flag or MINECRAFT_ROOT or os.getcwd()),
+                log_level,
+                action_kwargs,
+            )
 
     enderchest_parser.print_help(sys.stderr)
     sys.exit(1)
diff --git a/enderchest/test/test_cli.py b/enderchest/test/test_cli.py
index 5fdfc37..7f833ec 100644
--- a/enderchest/test/test_cli.py
+++ b/enderchest/test/test_cli.py
@@ -79,7 +79,9 @@ class ActionTestSuite:
 
     def test_root_can_also_be_provided_by_systemenv(self, monkeypatch):
         monkeypatch.setenv("MINECRAFT_ROOT", "/mnt/drive/minecraft/")
-        _, root, _, _ = cli.parse_args(["enderchest", *self.action.split(), *self.required_args])
+        _, root, _, _ = cli.parse_args(
+            ["enderchest", *self.action.split(), *self.required_args]
+        )
         assert root == Path("/mnt/drive/minecraft/")
 
     @pytest.mark.parametrize(
```

**Comment by JayPankajPatel** [comment]
Oversite on my part, I have ran the recommit hooks to fix this. The documentation fix doesn't set the env var to persist between terminal sessions, should I add that in the quick start guide?

**Comment by OpenBagTwo** [comment]
Nah, that's not documentation, just my own commentary for testing—given that `enderchest` has that `root` argument there is literally no reason an end-user should ever set the root that way.

**Review by OpenBagTwo — APPROVED** [review]
LGTM!

**Pull request merged**
